volumes:
  postgres14_data:
    driver: local
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local

services:
  app:
    container_name: ztm_targeo_backend
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'ztm_targeo_backend'
    user: ztm
    ports:
      - 8888:80
    volumes:
      - ./:/var/www/html

  api_postgres:
    image: postgres:14.2
    volumes:
      - postgres14_data:/var/lib/postgresql/data
      - ./infrastructure/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: system_db
      POSTGRES_USER: system_user
      POSTGRES_PASSWORD: system_secret
    ports:
      - 5432:5432


networks:
  default:
    name: ztm_targeo
