services:
  app:
    build: ./docker/php
    container_name: ztm_targeo_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app_network
    ports:
      - "8000:8000"

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  node:
    image: node:20
    container_name: node_app
    working_dir: /app
    volumes:
      - .:/app
    command: ["sh", "-c", "npm install && tail -f /dev/null"]
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge